name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build binary
      run: |
        cd cmd && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip main.zip main

    - name: Test ApiServer Package
      run: cd pkg/apiserver/ && go test -v 

    - name: create zip file
      run: cd cmd && zip main.zip main

    - name: deploy lambda function
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ap-south-1
        function_name: my-function-from-action
        zip_file: ./cmd/main.zip
        handler: main
        memory_size: 128
        timeout: 10
        handler: foobar
        role: arn:aws:iam::115391213665:role/lambda-execution-role-s3-access
        runtime: go1.x


    
